---
title: "robert_scratchmd"
author: "bobbytables"
date: "12/4/2019"
output: html_document
---

```{r}
library(tidyverse)
library(tidyr)
library(fst)
library(plotly)
library(lubridate)
library(ggcorrplot)
library(zoo)
library(ggstance)
library(gganimate)
```


```{r}
rm(list=setdiff(ls(), c()))
gc()


data18 <- read_fst("data18-fixed.fst") %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "9E", "DL")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "VX", "AS")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "MQ", "AA")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "OH", "AA")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "AA", "AA - American Airlines")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "AS", "AA - Alaska Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "B6", "B6 - JetBlue Airways")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "DL", "DL - Delta Air Lines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "EV", "EV - ExpressJet Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "F9", "F9 - Frontier Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "G4", "G4 - Allegiant Air")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "HA", "HA - Hawaii Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "NK", "NK - Spirit Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "OO", "OO - SkyWest Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "UA", "UA - United Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "WN", "WN - Southwest Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "YV", "YV - Mesa Airlines")) %>%
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "YX", "YX - Republic Airways"))

airports <- read_fst("airport_data.fst")

cols <- c("AA - American Airlines"="#36ace2",
          "AA - Alaska Airlines"="#488509",
          "B6 - JetBlue Airways"="#16339f",
          "DL - Delta Air Lines"="#e01e32",
          "EV - ExpressJet Airlines"="#27446a",
          "F9 - Frontier Airlines"="#176642",
          "G4 - Allegiant Air"="#00569c",
          "HA - Hawaii Airlines"="#ca0f88",
          "NK - Spirit Airlines"="#fcec03",
          "OO - SkyWest Airlines"="steelblue",
          "UA - United Airlines"="#1530a2",
          "WN - Southwest Airlines"="#f9a817",
          "YV - Mesa Airlines"="#aaa9ad",
          "YX - Republic Airways"="black")
```

# Correlation Matrix of Numerical Variables (not enough data to be helpful)

```{r}
corr18 <- data18 %>% 
  mutate(
    DATE = as.numeric(ymd(FL_DATE) - ymd(20171231)),
    DESTINATION_AIRPORT = DEST_AIRPORT_ID - 10000
  ) %>% 
  select(DATE,DESTINATION_AIRPORT,CRS_DEP_TIME,DISTANCE,AIR_TIME,DEP_DELAY) 

corr <- cor(corr18,use = "complete.obs")
pmat <- cor_pmat(corr18, use = "complete.obs")
```


```{r fig.height=6, fig.width=6}
ggcorrplot(corr, hc.order = TRUE, p.mat = pmat, lab =T)+
    #theme_minimal()+
    scale_fill_viridis_c()
```


# Causes of Delay by day of the week

```{r fig.height=6, fig.width=6}
choice18 %>% 
  mutate(
    wkday = wday(FL_DATE,label = T)
  ) %>% 
  group_by(wkday,type) %>% 
  summarise(
    #Actual = mean(DEP_DELAY, na.rm = T),
    Carrier = mean(CARRIER_DELAY, na.rm = T),
    Weather = mean(WEATHER_DELAY, na.rm = T),
    NAS = mean(NAS_DELAY, na.rm = T),
    `Late Aircraft` = mean(LATE_AIRCRAFT_DELAY, na.rm = T),
    Security = mean(SECURITY_DELAY, na.rm = T)
  ) %>% 
  pivot_longer(
    cols = -c(wkday,type),
    names_to = "Cause",
    values_to = "Minutes"
  ) %>% 
  ggplot()+
  geom_col(aes(x=wkday,y=Minutes,fill=Cause), position="stack")+
  theme_minimal()+
  scale_fill_viridis_d()+
  labs(
    x = "Day of the Week",
    y = "Average Delayed Minutes (NA Removed)"
  )+
  facet_grid(Cause ~ type)+
  coord_flip()

```

# Causes of Delay by Airline

```{r fig.height=6, fig.width=6}
choice18 %>% 
  group_by(OP_UNIQUE_CARRIER,type) %>% 
  summarise(
    Carrier = mean(CARRIER_DELAY, na.rm = T),
    `Late Aircraft` = mean(LATE_AIRCRAFT_DELAY, na.rm = T)
  ) %>% 
  pivot_longer(
    cols = -c(OP_UNIQUE_CARRIER,type),
    names_to = "Cause",
    values_to = "Minutes"
  ) %>% 
  ggplot()+
  geom_col(aes(x=OP_UNIQUE_CARRIER,y=Minutes,fill=OP_UNIQUE_CARRIER))+
  theme_minimal()+
  scale_fill_manual(values = cols)+
  labs(
    x = "Airline",
    y = "Average Delayed Minutes (NA Removed)"
  )+  
  facet_grid(type ~ Cause) +coord_flip()

  
```

# Where can you go?

```{r}
library(tidyverse)
library(tidyr)
library(fst)
library(plotly)
library(lubridate)

rm(list=setdiff(ls(), c()))
gc()


data18 <- read_fst("data18-fixed.fst") %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "9E", "DL")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "VX", "AS")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "MQ", "AA")) %>% 
  mutate(OP_UNIQUE_CARRIER = replace(OP_UNIQUE_CARRIER, OP_UNIQUE_CARRIER == "OH", "AA"))
airports <- read_fst("airport_data.fst")
cols <- c("AA"="#36ace2",
          "AS"="#488509",
          "B6"="#16339f",
          "DL"="#e01e32",
          "EV"="#27446a",
          "F9"="#176642",
          "G4"="#00569c",
          "HA"="#ca0f88",
          "NK"="#fcec03",
          "OO"="steelblue",
          "UA"="#1530a2",
          "WN"="#f9a817",
          "YV"="#aaa9ad",
          "YX"="black")

choice <- "MSP"
typechoice <- "Departures"

sp <- airports %>% 
  filter(
    ORIGIN == choice
  )

choice18 <- data18 %>% 
  filter(
    ORIGIN_AIRPORT_ID == sp$ORIGIN_AIRPORT_ID | DEST_AIRPORT_ID == sp$ORIGIN_AIRPORT_ID
  ) %>% 
  mutate(
    type = ifelse(
      ORIGIN_AIRPORT_ID == sp$ORIGIN_AIRPORT_ID,
      "Departures",
      "Arrivals"
    )
  )

fltr18 <- choice18 %>% 
  filter(
    type == typechoice
  )

fltr18a <- read.csv(text="ORI_ID,DES_ID")
fltr18d <- read.csv(text="ORI_ID,DES_ID")

if (fltr18$type[1] == "Departures") {
  fltr18d <- fltr18 %>% 
    rename(
      ORI_ID = ORIGIN_AIRPORT_ID,
      DES_ID = DEST_AIRPORT_ID
    ) %>% 
    select(V1,FL_DATE,OP_UNIQUE_CARRIER,ORI_ID,DES_ID) %>% 
    group_by(ORI_ID,DES_ID,OP_UNIQUE_CARRIER) %>% 
    summarise(
      airline_n = n_distinct(V1)
    ) 
} else {
  fltr18a <- fltr18 %>% 
    rename(
      DES_ID = ORIGIN_AIRPORT_ID,
      ORI_ID = DEST_AIRPORT_ID
    ) %>% 
    select(V1,FL_DATE,OP_UNIQUE_CARRIER,ORI_ID,DES_ID) %>% 
    group_by(ORI_ID,DES_ID,OP_UNIQUE_CARRIER) %>% 
    summarise(
      airline_n = n_distinct(V1)
    ) 
}

fltr18m <- full_join(fltr18d,fltr18a)

rm(list=setdiff(ls(), c("fltr18m","airports","cols")))
gc()

fmax <- fltr18m %>% 
  group_by(DES_ID) %>% 
  summarise(
    max = max(airline_n)
  ) %>% 
  left_join(fltr18m, by = c("DES_ID"="DES_ID","max"="airline_n")) %>% 
  select(
    DES_ID, OP_UNIQUE_CARRIER
  )

fltr18g <- fltr18m %>% 
  group_by(ORI_ID,DES_ID) %>% 
  summarise(
    n = sum(airline_n)
  ) %>% 
  left_join(airports,
            by = c("ORI_ID" = "ORIGIN_AIRPORT_ID")) %>% 
  rename(ori_code = ORIGIN,
         ori_lat = lat,
         ori_lon = lon,
         ori_name = name) %>% 
  left_join(airports,
            by = c("DES_ID" = "ORIGIN_AIRPORT_ID")) %>% 
  rename(des_code = ORIGIN,
         des_lat = lat,
         des_lon = lon,
         des_name = name) %>% 
  left_join(fmax) %>% 
  rename(
    ori_id = ORI_ID,
    des_id = DES_ID,
    airline = OP_UNIQUE_CARRIER
  )

rm(list=setdiff(ls(), c("fltr18g","cols")))
gc()

geo <- list(
      #scope = "usa",
      projection = list(
      type = 'orthographic',
      rotation = list(lon = -100, lat = 40, roll = 0)
      ),
      showland = T,
      landcolor = 'transparent',
      countrycolor = 'transparent'
    )
    
p <- plot_geo() %>%
      add_segments(
        data = fltr18g, x = ~ori_lon, xend = ~des_lon,
        y = ~ori_lat, yend = ~des_lat,
        hoverinfo = "none",
        color = ~airline,
        colors = cols,
        alpha=.175#, size=I(linesize)
      ) %>% 
      add_markers(
        data = fltr18g, x = ~des_lon, y = ~des_lat, 
        text = ~paste("Airport:", des_code, "|",des_name, "<br>Airline with most flights:", airline), 
        hoverinfo = "text",
        size = ~n^2, 
        alpha=1,
        color = ~airline,
        colors = cols
      ) %>% 
  add_markers(
        data = fltr18g, x = ~ori_lon, y = ~ori_lat, 
        text = ~paste(ori_code, "|", ori_name), 
        hoverinfo = "text",
        size = I(10),
        symbol = I("star"),
        color = I("red")
      )

rm(list=setdiff(ls(), c("p","geo")))
gc()
    
ggplotly(p) %>% 
      layout(
        title = 'How connected is your airport, and which carriers?',
        geo = geo, showlegend = TRUE,
        plot_bgcolor='transparent',
        paper_bgcolor='transparent'
      )
```

```{r}
data18
```

# Animated Bar Chart of Adjusted Delay Minutes

```{r}
sorted <- data18 %>% 
  group_by(FL_DATE,OP_UNIQUE_CARRIER) %>% 
  summarise(
    n0=mean(DEP_DELAY,na.rm=T)
  ) %>% 
  group_by(OP_UNIQUE_CARRIER) %>% 
  mutate(
    cumsum=cumsum(n0)
  ) %>% 
  select(
    date=FL_DATE,
    carrier=OP_UNIQUE_CARRIER,
    cumsum=cumsum
  )

carriers <- unique(sorted$carrier)  # vector of all carriers
dates <- unique(sorted$date)  # vector of all dates

cts <- data.frame(carrier=carriers, date=as.Date("2017-12-31"),cumsum=as.integer(0)) 
# adding baseline of 0

sorted2 <- sorted %>% 
  expand(carrier,date=dates)

sorted3 <- left_join(sorted2,sorted)

sorted4 <- bind_rows(sorted3, cts) %>% # adding 1899 baseline to sorted df
  arrange(carrier,date) %>% 
  na.locf()

sorted5 <- sorted4 %>% 
  group_by(date) %>% 
  mutate(rank=rank(-cumsum,ties.method="first")) %>% 
  group_by(carrier) %>% 
  ungroup()

options(digits=2)

statplot <- sorted5 %>% 
  ggplot(aes(x= cumsum, y=rank,color=as.factor(carrier)))+
  geom_barh(stat = "identity", aes(fill=carrier))+   
  geom_text(aes(x=0,color=carrier, label = paste(carrier, " ")),vjust=0.2,hjust=1) +
  geom_text(aes(x=cumsum,label=paste("", trunc(cumsum))),vjust=.5,hjust = 0)+
  scale_y_reverse()+
  coord_cartesian(clip="off",expand=F)+ # disallows clipping of the axes
  guides(color = F, fill = F) +
  scale_fill_manual(values = cols)+
  scale_color_manual(values = cols)+
  theme_minimal()+
  theme(legend.position = "none",
        plot.margin = unit(c(1,1,1,4), "cm"),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_blank())

p <- statplot +
  transition_states(states = date,transition_length = 6, state_length = 4)+
  view_follow(fixed_y=T)+
  ease_aes('quadratic-in-out')+
  enter_drift(x_mod = -1) + exit_drift(x_mod = 1) +
  labs(title = "Race to the bottom: Airline delay minutes",
       x="Accumulated delay minutes, adjusted for number of flights",
       y="",
       caption='{closest_state}')

animate(p,
        nframes = length(unique(sorted5$date))*2,
        fps=24, 
        width=900, 
        height=800)
```


